config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :posts
  resources :users
  resources :rooms
  root "myuser#show"
  resources :articles
  get "myuser/show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :users, through: :entries
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @currentEntries = current_user.entries
    #@currentEntriesのルームを配列にする
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    #@currentEntriesのルーム且つcurrent_userでないEntryを新着順で取ってくる
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: @user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    #present?の戻り値は真偽値。よって、trueの場合、
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @direct_messages = @room.direct_messages
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "DM")
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end


end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="container">
  <br>
  <div class="headfix">
  <h1 class="headfont">トーク</h1>
  </div>

  <br>
  <% @anotherEntries.each do |e| %>

    <table class="table table-striped">
        <tr>
            <td>
  　　　　　　　　　<!-- 名前からroomの詳細に飛べるようにリンク化 -->
                <%= link_to room_path(e.room.id) do %>

                    <%= e.user.username %>
                <% end %>
            </td>
            <td>
               <!-- 最新メッセージ内容の最初の7文字を表示する -->
                <% dm = DirectMessage.find_by(id: e.room.direct_message_ids.last).name %>
                <%= truncate(dm, length: 10) %>
            </td>
            <td>
                <h6 style="color: #C0C0C0;"><%= e.updated_at.strftime("%Y/%m/%d %H:%M") %></h6>
            </td>
            <td>
               <!-- ゴミ箱アイコンクリックでroomを消せるようにする -->
                <%= link_to room_path(e.room.id), method: :delete do %>
                    <i class="fas fa-trash" style="color: black;"></i>
                <% end %>
            </td>
        </tr>
    </table>


  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="talkroomwrap">

  <div class="talkheader">
    <% @entries.each do |e| %>
       <!-- eachで回したentryユーザーがログインユーザーであれば、@classに"current_user"の文字列を代入する。ログインユーザーであれば、空白を代入する -->
        <% current_user == e.user ? @class = "current_user" : @class = ""  %>
           <!-- eachで回したentryユーザーがログインユーザーでなければ、entryユーザー名を表示する -->
            <% if e.user != current_user %>
               <h5 class="text-left <%= @class %>" id="<%= @class %>" style="font-size: 30px;" data-id="<%= e.user.id %>"><%= link_to "@#{e.user.username}", user_path(e.user_id) %></h5>
            <% else %>
               <h5 class="text-left <%= @class %>" id="<%= @class %>" data-id="<%= e.user.id %>"></h5>
            <% end %>
    <% end %>
  </div>
  <div class="container mr-0 pr-0">
    <!-- メッセージ内容は、パーシャルにします -->
    <div class="talkdetail" id="direct_messages" data-room_id="<%= @room.id %>">
        <%= render @direct_messages %>
    </div>
  </div>




  <div class="talkfooter">
    <!-- メッセージフォーム -->
    <form>
        <label style="color: white;" id="target">新しいメッセージを作成</label><br>
        <input type="text" id="chat-input" data-behavior="room_speaker" class="form-control formwidth">
    </form>
  </div>


</div>

<!--
<script>
    //トークルーム遷移時に入力フォーム記載場所にスクロールする(最新トークは下にあるため)
    var element = document.getElementById('target'); // 移動させたい位置の要素を取得
    var rect = element.getBoundingClientRect();
    var position = rect.top;
    setTimeout( function() {
        scrollTo(0, position);}
        , 1000);
</script> -->