config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :posts
  resources :users
  resources :rooms
  root "myuser#show"
  resources :articles
  get "myuser/show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/customize.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  </head>

  <body class="text-center">
  <main class="wrapp">

<div class="row rowwrapp m-0">
  <div class="col-lg-1 col-md-1 col-sm-2 col-2 headerclass p-0">
    <div class="row mb-5 flexdesign">
      <div class="col-12 p-0 ">
         <%= link_to myuser_show_path, class: "nonedeco" do %>
  <i class="bi bi-person-fill fontcolor"></i>
      <% end %>
      </div>
    </div>
    <div class="row mb-5 flexdesign">
      <div class="col-12 p-0 ">

   <%= link_to rooms_path do %>
        <i class="bi bi-chat-dots-fill fontcolor"></i>
   <% end %>
      </div>
    </div>


    <div class="row mb-5 ml-2 flexdesign">
      <div class="col-12 p-0 ">
        <%= link_to users_path do %>
        <i class="bi bi-people-fill fontcolor"></i>
        <% end %>
      </div>
    </div>




  </div>
  <div class="col-lg-11 col-md-11 col-sm-10 col-10 p-0 mainview">

  <% if request.path.include?('rooms/') %>
  <% else %>
  <div class="logodisplay">
  <p class="text-primary fw-bold mx-3 mt-2">LINK</p>
  </div>
  <% end %>



  <%= yield %>
  </div>
</div>




  </main>

  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/customize.css" rel="stylesheet">

  </head>

  <body class="text-center">

<div class="itemsalign">
    <%= yield %>
</div>

  </body>
</html>